### ISSUE TITLE
Pick a good way to parse XML

### ISSUE THREAD

**Issue by porglezomp** [porglezomp-misc/umich-dining#4]

**Comment by porglezomp** [comment]
Out of SAX vs DOM, we want something that will give us a DOM so we don't have to write tons of code. We can change later for performance if we care.

With a DOM, the question is what kind of DOM we want. Do we just want nested hashes, or would we like something with XPath queries, etc. It seems like XPath might be more robust, but we should see what the different libraries are like.

**Comment by OkayHughes** [comment]
I'm thinking we could definitely parse it using a SAX parser, because installing dependencies is annoying.

**Comment by porglezomp** [comment]
Sure, we'll use the Foundation `XMLParser` for now.
